### ISSUE TITLE
Improve documentation of closestLayerSnap()

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Leaflet.GeometryUtil#22]
See https://github.com/makinacorpus/Leaflet.GeometryUtil/issues/21#issuecomment-62884968

**Comment by mdartic** [comment]
The documentation has been updated to be more easy to understand.

See the documentation method 
http://makinacorpus.github.io/Leaflet.GeometryUtil/global.html#closestLayerSnap

Hope this will help others to not lose some time to understand...
