### ISSUE TITLE
Using closest function with GeoJSON layer

### ISSUE THREAD

**Issue by rossanag** [makinacorpus/Leaflet.GeometryUtil#23]
Hi, I thought it could be used because L.geoJson implements ILayer, however I can't get it working.
The GeoJson file is a set of points (markers) which is being properly rendered.

The error: *Uncaught TypeError: Cannot read property 'lat' of null* . It happens at 'closest' function within the code.
It refers to "distanceSegment: function (map, latlng, latlngA, latlngB) "
Thanks!

    function nearestBiciAmigo()
    {		  		
 		if (typeof latlngmap != "undefined")
		{
			if ((latlngmap.lat != null) && (latlngmap.lng != null))
			{		
							
				var nlatlng = L.GeometryUtil.closest(mapa, geoBiciAmigos.getLayers() ,latlngmap); 																
				mapa.setView(nlatlng,13); 									
			}
			else
				alert("Click sobre el lugar");					
        }        
        else
        	alert("Click sobre el lugar");
    }

**Comment by mdartic** [comment]
@rossanag I've implemented your use case in the `closestLayer` .
Check the 0.5.1 version of the plugin to see if it's better now.

**Comment by mdartic** [comment]
@rossanag the last version 0.7.1 fix a bug of the method `closest` used by `closestLayer`.
Please prefer use this last version.
Don't hesitate to reopen the issue if needed.

**Comment by ayushjoshi1** [comment]
@mdartic I am pretty much having the same issue here but I couldn't get the "Cannot read properties of null (reading 'lat')" error to get resolved. Im not sure where the error is coming from.

`map.on('click', function(e) {
  
  const coordinates_array = geojsonLayer.getLayers().map(l => l.feature.geometry.coordinates)
  let closest_latlng = L.GeometryUtil.closestLayer(map, coordinates_array, e.latlng)
 
  // display the closest points
  markerClosestPolyline1 = L.marker(closest_latlng).addTo(map).bindPopup('Closest point on polyline1');
})`

**Comment by ayushjoshi1** [comment]
@mdartic I am pretty much having the same issue here but I couldn't get the "Cannot read properties of null (reading 'lat')" error to get resolved. Im not sure where the error is coming from. 

var geojsonLayer = new L.GeoJSON.AJAX("XXX.geojson", {
    style: {color: 'red', 
            weight: 4}
});       
geojsonLayer.addTo(map);
const coordinates_array = geojsonLayer.getLayers().map(l => l.feature.geometry.coordinates)

markerClosestPolyline1 = null

map.on('click', function(e) {
  
  const coordinates_array = geojsonLayer.getLayers().map(l => l.feature.geometry.coordinates)
  let closest_latlng = L.GeometryUtil.closestLayer(map, coordinates_array, e.latlng)

  markerClosestPolyline1 = L.marker(closest_latlng).addTo(map).bindPopup('Closest point on polyline1');
})
