### ISSUE TITLE
Array<Array<L.LatLng>>

### ISSUE THREAD

**Issue by domialex** [makinacorpus/Leaflet.GeometryUtil#24]
It is possible that some features have an Array of Arrays of LatLngs instead of a single imbrication.
The plugin does not support this right now.

**Comment by fredericbonifas** [comment]
Hi,
Could you please precise a little bit more what your are thinking about and ideally provide a jsfiddle so this problem can be investigated ?

Thanks !

**Comment by domialex** [comment]
Here's an example:
```javascript
var point = map.getCenter(); // Center of the map.
var latlngs = someFeature.getLatLngs(); // All the points of the feature. (A polyline)
var closestPoint = L.GeometryUtil.closest(map, latlngs, point); // Get the closest point of the feature from the center of the map.
```
This code will fail if the feature returns getLatLngs() with Array<Array<L.LatLng>> instead of Array<L.LatLng>.
Not all features have this, but there are cases where this double imbrication can occur.

**Comment by kaynz** [comment]
Any updates on this?

**Comment by leplatrem** [comment]
I don't see any pull request, no ;)

With domialex feedback there should be a way to write a small tests and propose something!

Don't hesitate!

**Comment by LePat** [comment]
In GeoJSON, polygon are Array<Array<L.LatLng>>

The function closest work on Array<L.LatLng> and should be changed to manage Polygons:
`
		var latlngs;
		if (layer instanceof L.Polygon) {
			latlngs = layer.getLatLngs()[0].slice(0);
		} else {
			latlngs = layer.getLatLngs().slice(0);
		}
`

like it is done further (the push of the first vertex)

It will not manage "holes" in the polygon because it only take the first Array of LatLngs but it returns at least the closest Feature.

**Comment by mdartic** [comment]
@LePat thanks for your proposition, don't hesitate to make a PR and upgrade tests if you have some time.

But, tell me if I'm wrong, you're using leaflet 1.0, isn't it ?

If this is the case, GeometryUtil haven't been correctly tested for 1.0, so unfortunately, it's normal.

**Comment by mdartic** [comment]
@domialex @kaynz @LePat 
if you have time, don't hesitate to test the 0.6.0 of the plugin.
I implement nested arrays for `closest` method, it works for my use cases, but maybe some of you have others use cases.
It would be nice to have your feedback.

**Comment by mdartic** [comment]
The last version, 0.7.1 has been tested in #46 and it seems working nicely now.
I close the issue.
