### ISSUE TITLE
Publish latest version on npm

### ISSUE THREAD

**Issue by MPieter** [makinacorpus/Leaflet.GeometryUtil#30]
Could you make this package available on npm ? 
Useful for use with browserify for example.

**Comment by leplatrem** [comment]
I believe that is the case. Probably not up to date...
@fredericbonifas can you confirm?

https://www.npmjs.com/package/leaflet-geometryutil

**Comment by MPieter** [comment]
Indeed, I found that one but that's not the latest.

Latest: 0.4.0
NPM: 0.3.2

**Comment by MPieter** [comment]
Maybe you should on https://www.npmjs.com/package/leaflet-geometryutil also link to the GitHub page, to avoid confusion.

**Comment by leplatrem** [comment]
I updated NPM and the readme :)

Thanks for the feedback !
