### ISSUE TITLE
Does this support Leaflet 1.0?

### ISSUE THREAD

**Issue by gholol** [makinacorpus/Leaflet.GeometryUtil#45]
Title says it all... I couldn't find any info on this regard.

**Comment by SBats** [comment]
Hi @gholol, thanks for asking. We haven't tested it yet.
We are currently working on cleaning and refactoring all our plugins, then we will test and fix them for leaflet v1.

If you have time to try it yourself, please, do not hesitate to give us feedbacks and/or make a pull-request with the proper fixes.

**Comment by mdartic** [comment]
After testing with leaflet 1.0, several functions don't work correctly.
Some work need to be done to achieve compatibility.
A specific branch will be open soon, but, as @SBats says, don't hesitate to test, report issues and/or submit PR.
We will be glad to review your code :)
