### ISSUE TITLE
Function "closest" is not working for polygons in leaflet 1.0

### ISSUE THREAD

**Issue by aver-ua** [makinacorpus/Leaflet.GeometryUtil#46]
This problem is due to nested arrays of latlngs.
Works only for polyline.
Function is not working for multipolyline, polygon, multipolygon.

**Comment by mdartic** [comment]
Not sure it is related to leaflet 1.0, but just because closest works with `Array<L.LatLng>` or `L.PolyLine` ?
See documentation file:///home/mdartic/workspace/makina/Leaflet.GeometryUtil/docs/global.html#closest .
Seems related to #24 
Have you seen it already ?

What do you think about it ?

**Comment by aver-ua** [comment]
Yes, You are right. The issue is related to #24.
In Leaflet 0.7 the function also works on polygon too, because structures of latlngs arrays are identical. So, I was thought, it is an undocumented feature :)
In my apps I use Leaflet.Snap. This plugin uses the function "closest" and all works fine even with polygons.
When I try to update to Leaflet 1.0, Leaflet.Snap stops working.
Could You please look at this modified code of the function https://jsfiddle.net/nff2uge7/2/
Is it correct?

**Comment by mdartic** [comment]
Indeed, Polygons are accepted but undocumented actually.
I've create an issue for that. cf #51
For leaflet 1.0, we don't have tested our libraries, so as L.Polyline & L.Polygon could return now nested arrays, it's not yet implemented in GeometryUtil.
I'm not sure your code is ok, but it has to be tested.
We will open a specific branch for testing purposes on Leaflet 1.0 soon.

**Comment by mdartic** [comment]
I've started a plunker to test these differents methods, around closest.

You can see [here](https://plnkr.co/edit/vbk6e6qiUMbz61zydM9x?p=preview)

You can change the leaflet to use 1.0 for example, directly in the head of index.html, and... it's actually not working, with polygon only, because polygon.getLatLngs return nested arrays. (in this example)

So, for the moment, this library can't work with Polygons & Leaflet 1.0 .

The solution I think it's to flatten the array result of getLatLngs, and it could be useful for other use cases.
Need to be implemented, if you have some suggestions (recursive function, like your `extractLatLngs`) don't hesitate to submit a PR with some tests.

If not, I will spend some time to implement it later.

**Comment by aver-ua** [comment]
Mathieu, please check [my plunk](https://plnkr.co/edit/40YQoVxdEdlb5iCQjcm9?p=preview) for Leaflet 1.0

**Comment by mdartic** [comment]
Great job, it works also with leaflet 0.7.7 .
I need to check some features with 0.7.7 and implement some tests.
I look for it today.

**Comment by mdartic** [comment]
I've implemented nested arrays in 0.6.0, so if you could test and write some feedback, it could be nice.

**Comment by kaynz** [comment]
Why don't you use `L.Polyline._flat`?

**Comment by aver-ua** [comment]
Mathieu, I tested 0.6.0 with Leaflet 1.0. All ok!
Thanks!

**Comment by mdartic** [comment]
@kaynz, where would you use `L.Polyline._flat` ? 
Actually, my problem is that this function doesn't exist in 0.7.7 .

@aver-ua I understand, I check that with a new test and implement this use case.

**Comment by kaynz** [comment]
Ah, okay. You're trying to support both leaflet versions with one library. So what about creating a shim?

**Comment by mdartic** [comment]
@kaynz well, I don't really know how to implement it. 
`closest` method need to be implemented for leaflet 0.7.7 & 1.0.0, but maybe we can optimize with your idea. 
If you have time, don't hesitate to make a PR.

@aver-ua I've made some improvements, but in the current implementation, which is closed to what you write in your [plunker](https://plnkr.co/edit/40YQoVxdEdlb5iCQjcm9?p=preview), there is a mistake.
If we define A the first point of the first polygon, and B the first point of the second polygon (hole).
If we search the `closest` point near the segment A-B, in fact we get a point of this segment.
This is not correct.

So, the current implementation is not right, I have to change the algorithm.
I work on it.

If you have comments, don't hesitate.

**Comment by leplatrem** [comment]
I would recommend to keep the code light and clean by focusing on Leaflet
1.0.
Legacy apps can still rely on old pinned versions, or upgrade to 1.0 for
new features.
(My 2 cents)

Le 12 sept. 2016 16:14, "Mathieu DARTIGUES" <notifications@github.com> a
écrit :

**Comment by aver-ua** [comment]
@mdartic 
I check new version of "closest" (with last segment). Works great, no problem.
Thanks!

**Comment by mdartic** [comment]
@aver-ua Great, I close the issue.

@leplatrem well, I agree with you, and I try to respect this guideline.
the fact is that, in 0.7.7, there are sometimes nested array, so I thought it would have been useful for 0.7.7 users. And there were issues for this.
so, as the need is the same, I think it's better to have the `closest` method compatible with nested arrays for both leaflet 0.7.7 & 1.0.0 .
hope this choice will be the right. we'll see in the future ;-)
