### ISSUE TITLE
Use daux.io for documentation

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Leaflet.GeometryUtil#6]
https://github.com/justinwalsh/daux.io

**Comment by mdartic** [comment]
Hello Mathieu, 

I'm going to spend some time on this plugin, and on LayerIndex.

For this issue, do you still think it's a good idea to use daux.io ?

It's in PHP, so I was asking me if it was a good thing to use a different language in this plugin ?

I would prefer keep using jsdoc, but with a different theme, like this one :

http://docstrap.github.io/docstrap/themes/cosmo/

I test on GeometryUtil, and it gives that :

https://mdartic.github.io/Leaflet.GeometryUtil/minami/

or

https://mdartic.github.io/Leaflet.GeometryUtil/ink-docstrap/

What do u think about ?

**Comment by leplatrem** [comment]
Hello!
I'm very happy to see some activity here! Big up for taking over!! 
Both look great, minami is super slick and clean!! ink-docstrap has a nice responsive layout (not sure there's a use case)...
Do what you think it's best! It's all yours ;)

**Comment by mdartic** [comment]
Thanks @leplatrem 
So, I'm gonna use minami theme.
Hope devs will like it.
