### ISSUE TITLE
Please provide complete source tarball

### ISSUE THREAD

**Issue by Natureshadow** [makinacorpus/Leaflet.GeometryUtil#65]
Please provide a complet esource tarball, inbcluding the sources for docs/ and everything else needed for a complete build. At the very least, alle make targets should work from the source tarball.

Please, if possible, also provide a changelog and sign the release tarball.

**Comment by leplatrem** [comment]
Are you sure that you wanted to address these in this repo?
The tarball is something that Github offers, we don't use make, and the changelog is basically in the readme.
I'm sure we can improve what we have though :) feel free to open a PR or be more precise...

**Comment by Natureshadow** [comment]
@leplatrem Well…

`
$ wget https://github.com/makinacorpus/Leaflet.GeometryUtil/archive/v0.4.0.tar.gz
$ tar xvzf v0.4.0.tar.gz
[…]
Leaflet.GeometryUtil-0.4.0/Makefile
`

I also see that there is no Makefile anymore, but in the v0.4.0 release/tag, there is, and the tests and docs are missing, as I described above.

I have no idea how it got there, but as the tarballs are just git-archive exports from a tag, I assume then that this broken state was the state of the repo at tag time ;).

Source tarballs are still the best source form for distributions (GeometryUtil has become a part of Debian today), so just please make sure whatever tarballs you publish are correct (and, as an advise, please create them thoughtfully, not just as a side product of tagging).

**Comment by Natureshadow** [comment]
Oh, and having said al lthat… there seem to have been a lot of changes and even release versions since the last published 0.4.0. Could you please push all tags and also create a source tarball for the most recent release version, so we can get something current into Debian instead of 0.4.0 ;)?

**Comment by necramirez** [comment]
I would like to echo the previous comment:
> Could you please push all tags

I watch for releases in Github, but because the releases here are not updated, I wouldn't know if something new was published to npm

**Comment by leplatrem** [comment]
It should be better from now on, now that @haoliangyu gives a hand :)

**Comment by haoliangyu** [comment]
I will add the current release (v0.8.1) tonight.

**Comment by haoliangyu** [comment]
@leplatrem In fact I think it may be better to publish v0.8.2 since the current master branch has more content (#71 and #72) than the v0.8.1.

**Comment by haoliangyu** [comment]
The release history is completely rebuilt. Source tarballs are available at the release page now. I am closing this issue. If there is any other question, please comment.
