### ISSUE TITLE
Doesn't work with leaflet 1.1.0

### ISSUE THREAD

**Issue by ParAnton** [makinacorpus/Leaflet.GeometryUtil#68]
The function Leaflet.Polyline._flat has been moved to Leaflet.LineUtil._flat so this has to be updated to make it work with Leaflet 1.1.0
[](https://github.com/Leaflet/Leaflet.Editable/issues/130)

**Comment by haoliangyu** [comment]
I also have this problem while trying to use this library with Leaflet 1.2. A PR #69 has been submitted to resolve it.
