### ISSUE TITLE
Distance function : Cannot read property 'distance' of undefined

### ISSUE THREAD

**Issue by alizeegly** [makinacorpus/Leaflet.GeometryUtil#88]
Hello, 
I'm developing a map in vuejs using leaflet, and I want to use GeometryUtil to calculate the distance between two points. For that, I use the tuto distance-length but when I use the function I got an error in the console :
Cannot read property 'distance' of undefined

>var firstLatLng = {lat:48.858372,lng:2.294479};
>var secondLatLng = {lat:48.847258,lng:2.352742}
>var distance = L.GeometryUtil.distance(map, firstLatLng, secondLatLng)
>console.log(distance)

Is this because I'm using vuejs or because I didn't use well the function?

Thank you for your help

**Comment by mdartic** [comment]
Hello,

Could you make a repo for testing ?

I think your import of the lib is not working as you may think.

**Comment by alizeegly** [comment]
I just find out while it wasn't working, I don't declare the variable outside my function, thank you for your quick response !

**Comment by mdartic** [comment]
Ok, I let you close the issue if it's ok for you.
