### ISSUE TITLE
Npm package not updated

### ISSUE THREAD

**Issue by enrico-calzavara** [makinacorpus/Leaflet.GeometryUtil#92]
Hi, 
the latest published npm package has a dependency on leaflet >=0.7.0, that is causing a misalignment on leaflet versions after a npm install:

<img width="300" alt="Screenshot 2021-04-06 at 17 49 59" src="https://user-images.githubusercontent.com/2581454/113739890-87425e80-9700-11eb-845e-e1863c3ea759.png">

In master branch the dependency on leaflet is actually set to ^1.6.0: could you please update the npm package?

**Comment by leplatrem** [comment]
@gutard @submarcos @numahell :wave:

**Comment by mdartic** [comment]
@enrico-calzavara the latest npm package is now the 0.10.0, could you update your project and tell me if the problem is still here ?

If so, could you give us more information about your configuration, node & npm version ?

**Comment by enrico-calzavara** [comment]
It works, thanks!
